# Makefile runs generatelistofmissingfiles, generatedocumentation, and appendversions in that order

run:
#	./copymodules.sh 
	./generatelistofmissingfiles.sh
	./generatedocumentation.sh
	./appendversions.sh
